### ISSUE TITLE
Erro no backend

### ISSUE THREAD

**Issue by diogom3lo** [diogom3lo/projetoPW#6]
está a dar um erro no backend ao usar o frontend:

 -=> Valid Token <=-
DECODED->{
  "id": "6662ca04a7d03b8decc89df6",
  "name": "Melo",
  "iat": 1717874956,
  "exp": 1717963356
}
route scopes: [ 'read-all', 'read-posts' ]
User scopes: undefined
TypeError: Cannot read properties of undefined (reading 'includes')
    at /Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/data/users/service.js:22:70
    at Array.some (<anonymous>)
    at /Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/data/users/service.js:22:45
    at Layer.handle [as handle_request] (/Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/layer.js:95:5)
    at /Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/node_modules/express/lib/router/index.js:280:10)
    at /Users/diogomelo/Documents/ESCOLA/2º Periodo/PW/PROJETO/server/product.js:29:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Provavelmente é no service.js mas ainda nao tenho a certeza disso**

**Comment by diogom3lo** [comment]
Agora dá um novo erro: 
-=> Valid Token <=-
DECODED->{
  "id": "6662ca04a7d03b8decc89df6",
  "name": "Melo",
  "iat": 1718099451,
  "exp": 1718187851
}
route scopes: [ 'read-all', 'read-posts' ]
User scopes: undefined
User scopes are undefined or not an array

**Acredito que seja ao registrar o user na parte de "role" (quando pomos no postman na parte de role pomos "admin"), provavelmente vai ter que se criar uma coleção de roles em que cada role tem os seus scopes. Exemplo:**

// 1. Define Role Schema
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const roleSchema = new Schema({
    name: { type: String, required: true },
    scopes: [{ type: String }] // Assuming scopes are strings
});

const Role = mongoose.model('Role', roleSchema);

// 2. Define roles with associated scopes
const rolesData = [
    {
        name: 'Admin',
        scopes: ['read-all', 'manage-posts', 'read-posts'] // Example scopes
    },
    {
        name: 'User',
        scopes: ['read-posts'] // Example scopes for a regular user
    }
    // Add more roles as needed
];

// 3. Create roles in the database
async function createRoles() {
    try {
        await Role.deleteMany(); // Clear existing roles
        await Role.insertMany(rolesData); // Insert roles data
        console.log('Roles created successfully');
    } catch (err) {
        console.error('Error creating roles:', err);
    }
}

// Call the createRoles function to create roles during application startup
createRoles();

module.exports = Role;

**Comment by diogom3lo** [comment]
Ainda continua com erro mas agora é outro:

Decoded token roles: []
Decoded token scopes: []
route scopes: [ 'read-all', 'read-posts' ]
User scopes: []

**Ainda não sei o porque deste erro os scopes e as roles não estão a ser decodificadas ou não se consegue as definir. Mesmo usando o chatgpt não ajuda de grande coisa pois ele altera o código e continua igual o erro tanto este como nos outros acima. Por enquanto estou sem ideias do que fazer.**

**Comment by diogom3lo** [comment]
Consegui resolver o erro mudando algumas coisas no código mas nao sei o que fiz xD
